migrate snap to core24 + update minimum python version to 3.10
canonical/awspub pull request #73
Opened 2024-12-12 20:45 UTC by rthill91

2024-12-13 07:27 UTC, toabctl requested changes
please split those commits
* use poetry plugin
* snap: use core24
* bump minimal python version
*

2024-12-13 07:27 UTC, toabctl commented on snap/snapcraft.yaml
> +    plugin: poetry
unrelated to the commit message.

2024-12-13 12:02 UTC, rpocase submitted a review, later dismissed
lgtm pending tom's requested changes

2024-12-16 08:57 UTC, toabctl requested changes
we try to follow conventional commits (see `git log`) so please add commit types and also a brief reasoning for each commit.

2024-12-16 18:23 UTC, JessicaJang approved these changes

2024-12-17 08:56 UTC, toabctl approved these changes

2024-12-17 08:56 UTC, merged